name: Continuos Integration Backend

on:
  pull_request:
    branches: ["main"]
    paths:
        - 'backend/**'
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
      - '.github/workflows/deployBackend.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4

      - name: Configura Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        working-directory: backend
        run: mvn clean install

      - name: Teste Backend
        working-directory: backend
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        
      - name: Instalacao Railway cli
        run: npm install -g @railway/cli

      - name: Deploy Backend
        working-directory: backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service backend-app-service
